# # Usa um banco em memória que não exige servidor externo
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Diz para o Hibernate não tentar validar nada no MySQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

# URL para integração de API externa (substituir por endpoint real)
external.api.base-url=https://api.example.com